- hosts: localhost
  connection: local 
  gather_facts: False 
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    
    - name: Create vprofile VPC
      ec2_vpc_net: 
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - name: Create Public subnet 1 in zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub1Cidr}}"
        state: "{{state}}"
        az: "{{zone1}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create Public subnet 2 in zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub2Cidr}}"
        state: "{{state}}"
        az: "{{zone2}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create Public subnet 3 in zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub3Cidr}}"
        state: "{{state}}"
        az: "{{zone3}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: Create Private subnet 1 in zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub1Cidr}}"
        state: "{{state}}"
        az: "{{zone1}}"
        map_public: no
        resource_tags:
          Name: vprofile-privsub1
      register: privsub1_out
    
    - name: Create Private subnet 2 in zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub2Cidr}}"
        state: "{{state}}"
        az: "{{zone2}}"
        map_public: no
        resource_tags:
          Name: vprofile-privsub2
      register: privsub2_out

    - name: Create Private subnet 3 in zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub3Cidr}}"
        state: "{{state}}"
        az: "{{zone3}}"
        map_public: no
        resource_tags:
          Name: vprofile-privsub3
      register: privsub3_out

